#!/usr/bin/env python3

import sys

path = '/sys/class/backlight/intel_backlight/'
levels = [0, 0.007, 0.014, 0.03, 0.05, 0.07, 0.1, 0.14, 0.2, 0.3, 0.5, 0.7, 1]

with open(path + 'max_brightness') as f:
	brmax = int(f.read())

with open(path + 'actual_brightness') as f:
	brfrac = int(f.read())/brmax

i = min([(abs(brfrac - l), i) for i, l in enumerate(levels)])[1]
inext = min(max(i + {'-': -1, '+': 1}[sys.argv[1]], 0), len(levels) - 1)
brnext = round(levels[inext]*brmax)

with open(path + 'brightness', 'w') as f:
	f.write(str(brnext))
